spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/building
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
